name: story_painter
description: This package provides drawing experince like in story editor of Instagram.
version: 0.0.4
homepage: https://github.com/furkansarihan/story_painter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: